// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: modules/item/itemPb/itemPb.proto

package nriny_shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// structure
type FindItemInIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindItemInIdsReq) Reset() {
	*x = FindItemInIdsReq{}
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindItemInIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindItemInIdsReq) ProtoMessage() {}

func (x *FindItemInIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindItemInIdsReq.ProtoReflect.Descriptor instead.
func (*FindItemInIdsReq) Descriptor() ([]byte, []int) {
	return file_modules_item_itemPb_itemPb_proto_rawDescGZIP(), []int{0}
}

func (x *FindItemInIdsReq) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindItemInIdsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*Item                `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindItemInIdsRes) Reset() {
	*x = FindItemInIdsRes{}
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindItemInIdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindItemInIdsRes) ProtoMessage() {}

func (x *FindItemInIdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindItemInIdsRes.ProtoReflect.Descriptor instead.
func (*FindItemInIdsRes) Descriptor() ([]byte, []int) {
	return file_modules_item_itemPb_itemPb_proto_rawDescGZIP(), []int{1}
}

func (x *FindItemInIdsRes) GetItem() []*Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Damage        int32                  `protobuf:"varint,4,opt,name=damage,proto3" json:"damage,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_modules_item_itemPb_itemPb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_modules_item_itemPb_itemPb_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_modules_item_itemPb_itemPb_proto protoreflect.FileDescriptor

const file_modules_item_itemPb_itemPb_proto_rawDesc = "" +
	"\n" +
	" modules/item/itemPb/itemPb.proto\"$\n" +
	"\x10FindItemInIdsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"-\n" +
	"\x10FindItemInIdsRes\x12\x19\n" +
	"\x04item\x18\x01 \x03(\v2\x05.ItemR\x04item\"v\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x05R\x06damage\x12\x1a\n" +
	"\bimageUrl\x18\x05 \x01(\tR\bimageUrl2H\n" +
	"\x0fItemGrpcService\x125\n" +
	"\rFindItemInIds\x12\x11.FindItemInIdsReq\x1a\x11.FindItemInIdsResB Z\x1egithub.com/Arismonx/nriny-shopb\x06proto3"

var (
	file_modules_item_itemPb_itemPb_proto_rawDescOnce sync.Once
	file_modules_item_itemPb_itemPb_proto_rawDescData []byte
)

func file_modules_item_itemPb_itemPb_proto_rawDescGZIP() []byte {
	file_modules_item_itemPb_itemPb_proto_rawDescOnce.Do(func() {
		file_modules_item_itemPb_itemPb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_item_itemPb_itemPb_proto_rawDesc), len(file_modules_item_itemPb_itemPb_proto_rawDesc)))
	})
	return file_modules_item_itemPb_itemPb_proto_rawDescData
}

var file_modules_item_itemPb_itemPb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_modules_item_itemPb_itemPb_proto_goTypes = []any{
	(*FindItemInIdsReq)(nil), // 0: FindItemInIdsReq
	(*FindItemInIdsRes)(nil), // 1: FindItemInIdsRes
	(*Item)(nil),             // 2: Item
}
var file_modules_item_itemPb_itemPb_proto_depIdxs = []int32{
	2, // 0: FindItemInIdsRes.item:type_name -> Item
	0, // 1: ItemGrpcService.FindItemInIds:input_type -> FindItemInIdsReq
	1, // 2: ItemGrpcService.FindItemInIds:output_type -> FindItemInIdsRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_item_itemPb_itemPb_proto_init() }
func file_modules_item_itemPb_itemPb_proto_init() {
	if File_modules_item_itemPb_itemPb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_item_itemPb_itemPb_proto_rawDesc), len(file_modules_item_itemPb_itemPb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_item_itemPb_itemPb_proto_goTypes,
		DependencyIndexes: file_modules_item_itemPb_itemPb_proto_depIdxs,
		MessageInfos:      file_modules_item_itemPb_itemPb_proto_msgTypes,
	}.Build()
	File_modules_item_itemPb_itemPb_proto = out.File
	file_modules_item_itemPb_itemPb_proto_goTypes = nil
	file_modules_item_itemPb_itemPb_proto_depIdxs = nil
}
